name: ArmorStands
version: '${project.version}'
main: dk.shadow.Main
api-version: 1.8
authors: [ Shad0wsense ]
description: none
website: sastore.dk
commands:
  armor:
    description: command med mange features.
    aliases: [ArmorStands, arm]